"""Pack fitted stage paintings into game/lua/gen/gf_bg_<key>.lua.

Input: game/build/bgfit/<key>.gpu.json (or .cpu.json) = whole painting, and
       game/build/bgfit/<key>.ground.json = bottom strip of the painting (optional).
The fits come from the primitive fitter (genshin-ugc feat/primitive-fitter-v2:
scripts/fit_primitives_v2.py + fit_primitives_gpu.py, free alpha): translucent rotated
ellipses / rectangles, panel-centred coordinates, y up, rotation = client localRotation z.

Shape record, 12 bytes: x+2048 (12 bit) y+2048 (12) w (12) h (12) | r (9) kind (1) | r g b a.

  python -X utf8 game/tools/build_stages.py [--max 1100] [--ground-max 420]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')
HERE = Path(__file__).resolve().parent
GAME = HERE.parent
sys.path.insert(0, str(HERE))
import artlib as A  # noqa: E402

FIT = GAME / 'build' / 'bgfit'
GEN = GAME / 'lua' / 'gen'
STAGES = {
    'mondstadt': ('蒙德 · 风起地', '风与蒲公英的牧歌之城'),
    'liyue': ('璃月 · 归离原', '契约与群岩之港'),
    'inazuma': ('稻妻 · 雷暴之境', '永恒之下的雷光'),
    'sumeru': ('须弥 · 赤王陵', '黄沙与智慧之国'),
    'fontaine': ('枫丹 · 白淞镇', '正义与水之都'),
    'natlan': ('纳塔 · 烟谜主', '战争与火的部族'),
    'snezhnaya': ('至冬 · 冰封车站', '冰之女皇的国度'),
}


def ground_fade(shapes, panel_h, band=0.42):
    # the ground strip dissolves upward into the backdrop: shapes lose alpha by how high their
    # top edge reaches into the top `band` of the strip (y is up, origin at the panel centre)
    top = panel_h / 2
    fade = panel_h * band
    out = []
    for s in shapes:
        reach = s['y'] + max(s['w'], s['h']) * 0.35
        k = max(0.0, min(1.0, (top - reach) / fade + 0.25))
        if k <= 0.06:
            continue
        c = list(s['c']) + ([] if len(s['c']) > 3 else [128])
        c[3] = int(c[3] * k)
        out.append(dict(s, c=c))
    return out


def pack(shapes, limit):
    # the fitter's later shapes are details on top: keep the order, cut from the end if needed
    shapes = shapes[:limit]
    b = bytearray()
    for s in shapes:
        x = max(0, min(4095, round(s['x']) + 2048))
        y = max(0, min(4095, round(s['y']) + 2048))
        w = max(1, min(4095, round(s['w'])))
        h = max(1, min(4095, round(s['h'])))
        r = round(s['r']) % 360
        kind = 1 if s['k'] == 'e' else 0
        v = (x << 36) | (y << 24) | (w << 12) | h
        b += v.to_bytes(6, 'big')
        b += ((r << 1) | kind).to_bytes(2, 'big')
        c = s['c']
        b += bytes([int(c[0]), int(c[1]), int(c[2]), int(c[3]) if len(c) > 3 else 128])
    return A.b64(bytes(b)), len(shapes)


def load(key, part):
    for name in ([f'{key}.gpu.json', f'{key}.cpu.json'] if part == 'full' else [f'{key}.ground.json']):
        p = FIT / name
        if p.exists():
            return json.loads(p.read_text(encoding='utf-8')), name
    return None, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--max', type=int, default=1100)
    ap.add_argument('--ground-max', type=int, default=420)
    a = ap.parse_args()
    built = []
    for key, (name, sub) in STAGES.items():
        full, src = load(key, 'full')
        if not full:
            continue
        ground, gsrc = load(key, 'ground')
        d, n = pack(full['shapes'], a.max)
        lines = [f'-- generated by game/tools/build_stages.py from game/build/bgfit/{src}'
                 + (f' + {gsrc}' if gsrc else '') + '; do not edit',
                 'return {',
                 f"key='{key}', name='{name}', sub='{sub}',",
                 f"w={full['panel'][0]}, h={full['panel'][1]}, bg={{{','.join(str(int(v)) for v in full['background'][:3])}}}, n={n}, d='{d}',"]
        if ground:
            gd, gn = pack(ground_fade(ground['shapes'], ground['panel'][1]), a.ground_max)
            lines.append(f"ground={{w={ground['panel'][0]}, h={ground['panel'][1]}, "
                         f"bg={{{','.join(str(int(v)) for v in ground['background'][:3])}}}, n={gn}, d='{gd}'}},")
        lines.append('}')
        (GEN / f'gf_bg_{key}.lua').write_text('\n'.join(lines) + '\n', encoding='utf-8')
        built.append((key, src, n, gsrc))
        print(key, src, n, 'ground' if gsrc else 'no ground')
    # index of available paintings
    keys = [b[0] for b in built]
    (GEN / 'gf_bglist.lua').write_text(
        '-- generated by game/tools/build_stages.py; do not edit\nreturn {' + ','.join(f"'{k}'" for k in keys) + '}\n',
        encoding='utf-8')


if __name__ == '__main__':
    main()
