"""Bake the title logo (drawn in tools/logo/logo.html, exported to tools/logo/logo.png) into
painter-ordered rectangles for the client: lua/gen/gf_logo.lua.

  python -X utf8 game/tools/build_logo.py [--preview]

Two tiers (hi / lo) at different resolutions. The picture is cut into column tiles below 256 px
so each tile fits the 5-byte rect format; the title scene draws one tile per frame.
"""
import argparse
import sys
from pathlib import Path

import numpy as np

sys.stdout.reconfigure(encoding='utf-8')
HERE = Path(__file__).resolve().parent
GAME = HERE.parent
sys.path.insert(0, str(HERE))
import artlib as A  # noqa: E402

SRC = HERE / 'logo' / 'logo.png'
OUT = GAME / 'lua' / 'gen' / 'gf_logo.lua'
TIERS = {'hi': {'scale': 0.56, 'colours': 14}, 'lo': {'scale': 0.4, 'colours': 11}}
TILE = 250


def crop_alpha(im):
    a = np.asarray(im)[..., 3]
    ys, xs = np.nonzero(a >= 128)
    return im.crop((int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1))


def lua_str(s):
    return "'" + s + "'"


def build(im, spec):
    small = A.downscale(im, spec['scale'])
    pal = A.build_palette([small], spec['colours'])
    idx = A.despeckle(A.apply_palette(small, pal))
    h, w = idx.shape
    if h >= 256:
        raise SystemExit(f'logo tier too tall: {h}px')
    # one colour layering for all tiles so seams line up
    counts = [(int((idx == c).sum()), c) for c in range(len(pal))]
    order = [c for _, c in sorted(counts, reverse=True)]
    tiles = []
    for x0 in range(0, w, TILE):
        sub = idx[:, x0:x0 + TILE]
        rects = A.painter(sub, order)
        tiles.append({'x': x0, 'n': len(rects), 'd': A.b64(A.pack_rects(rects)), 'rects': rects})
    return {'pal': pal, 'w': w, 'h': h, 'u': round(1 / spec['scale'], 4), 'tiles': tiles}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--preview', action='store_true')
    a = ap.parse_args()
    im = crop_alpha(A.load_rgba(SRC))
    lines = ['-- generated by game/tools/build_logo.py from game/tools/logo/logo.png; do not edit', 'return {']
    for tier, spec in TIERS.items():
        t = build(im, spec)
        pal = A.b64(bytes(v for c in t['pal'] for v in c))
        tl = ','.join(f"{{x={x['x']},n={x['n']},d={lua_str(x['d'])}}}" for x in t['tiles'])
        lines.append(f"{tier}={{w={t['w']},h={t['h']},u={t['u']},pal={lua_str(pal)},tiles={{{tl}}}}},")
        n = sum(x['n'] for x in t['tiles'])
        print(tier, f"{t['w']}x{t['h']}", 'colours', len(t['pal']), 'rects', n, 'tiles', len(t['tiles']))
        if a.preview:
            canvas = None
            from PIL import Image
            canvas = Image.new('RGBA', (t['w'], t['h']), (30, 34, 56, 255))
            for x in t['tiles']:
                part = A.render(x['rects'], t['pal'], min(TILE, t['w'] - x['x']), t['h'])
                canvas.alpha_composite(part.convert('RGBA'), (x['x'], 0))
            out = GAME / 'build' / f'logo-{tier}.png'
            out.parent.mkdir(parents=True, exist_ok=True)
            canvas.save(out)
            print('preview', out)
    lines.append('}')
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(OUT, OUT.stat().st_size, 'bytes')


if __name__ == '__main__':
    main()
