"""Bundle game/lua/*.lua (+ gen/) into the single client script the map mounts.

The 7.1 client loads one Lua file per script mapping and has no `require`/`load`, so every
module becomes a lazy loader behind a tiny require; gf_main.lua runs at top level (it defines
the lifecycle callbacks). Comment-only lines are stripped from game modules to save bytes.

  python -X utf8 game/tools/bundle.py            -> game/dist/genshin_fighter.lua
"""
from pathlib import Path
import hashlib
import re
import sys

sys.stdout.reconfigure(encoding='utf-8')
HERE = Path(__file__).resolve().parent
GAME = HERE.parent
SRC = GAME / 'lua'
OUT = GAME / 'dist' / 'genshin_fighter.lua'
ENTRY = 'gf_main'
MAX_BYTES = 7_500_000


def strip(text):
    out = []
    for line in text.splitlines():
        s = line.strip()
        if s.startswith('--') and not s.startswith('--[['):
            continue
        out.append(line.rstrip())
    return '\n'.join(out)


def modules():
    mods = {}
    for p in sorted(SRC.glob('gf_*.lua')):
        mods[p.stem] = strip(p.read_text(encoding='utf8'))
    for p in sorted((SRC / 'gen').glob('gf_*.lua')):
        mods[p.stem] = p.read_text(encoding='utf8')
    if ENTRY not in mods:
        raise SystemExit('missing entry module')
    return mods


def check_requires(mods):
    for name, text in mods.items():
        for dep in re.findall(r"require\('(gf_\w+)'\)", text):
            if dep not in mods:
                raise SystemExit(f'{name} requires unknown module {dep}')


def build(out=OUT):
    mods = modules()
    check_requires(mods)
    digest = hashlib.sha256(''.join(mods[n] for n in sorted(mods)).encode('utf8')).hexdigest()[:12]
    parts = [
        f'-- 原神格斗 v2 client bundle {digest}. Generated by game/tools/bundle.py; edit game/lua/*.lua.',
        f"GF_BUILD = '{digest}'",
        'local __loaders, __loaded = {}, {}',
        'local function require(name)',
        '    local m = __loaded[name]',
        '    if m == nil then',
        '        local f = __loaders[name]',
        "        if not f then error('module not bundled: ' .. tostring(name)) end",
        '        m = f()',
        '        __loaded[name] = m',
        '    end',
        '    return m',
        'end',
        'GF_REQUIRE = require',
    ]
    for n in sorted(mods):
        if n == ENTRY:
            continue
        parts.append(f"__loaders['{n}'] = function()\n{mods[n].rstrip()}\nend")
    parts.append(f'-- entry: {ENTRY}\n' + mods[ENTRY].rstrip())
    text = '\n'.join(parts) + '\n'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding='utf8', newline='\n')
    size = out.stat().st_size
    if size > MAX_BYTES:
        raise SystemExit(f'bundle too large: {size}')
    return out, size, digest


if __name__ == '__main__':
    path, size, digest = build()
    print(f'{path} {size} bytes {digest}')
