import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{decode,encode,msg,num,str,all,get}from'./node-gia-wire.mjs';
const source=process.argv[2],out=source?'outputs/network-node-sample4':'outputs/network-current-gia';mkdirSync(out,{recursive:true});
const b=source?readFileSync(source):readFileSync(out+'/'+JSON.parse(readFileSync(out+'/delivery.json')).filename),delivery=source?{filename:source.split(/[\\/]/).pop(),sha256:createHash('sha256').update(b).digest('hex')}:JSON.parse(readFileSync(out+'/delivery.json')),p=b.subarray(20,20+b.readUInt32BE(16)),r=decode(p);
assert.equal(b.readUInt32BE(0),b.length-4);assert.equal(b.readUInt32BE(16),b.length-24);assert(encode(r).equals(p));assert.equal(createHash('sha256').update(b).digest('hex'),delivery.sha256);
const graph=msg(msg(msg(msg(r,1),13),1),1),nodes=new Map(all(graph,3).map(x=>{const n=decode(x.v);return[num(n,1),n];})),defs=new Map();
for(const x of all(r,2)){const a=decode(x.v),d=msg(msg(msg(a,14),1),1),s=msg(d,107);let name='';for(const k of[101,102,108])name ||=str(msg(s,k),1);defs.set(num(msg(a,1),4),{signal:name,kind:str(a,3),data:d});}
if(source){const bindings=JSON.parse(readFileSync('work/network-signal-bindings.json')),reverse=Object.fromEntries(Object.entries(bindings).map(([a,b])=>[b,a]));for(const d of defs.values())d.signal=reverse[d.signal]||d.signal;}
const pin=(n,k,i=0)=>all(n,4).map(x=>decode(x.v)).find(p=>num(msg(p,1),1)===k&&num(msg(p,1),2)===i);
const inputs=['Slot','Role1','Role2','Role3','Ready','Stage','Epoch','Revision','Round','Wins1','Wins2'],flowParams=['Slot','Action','Epoch','Revision'],frameParams=['Slot','FirstFrame','AckFrame','Payload','Epoch'];
for(const [name,kind,params]of[['FighterTeam','监听信号',inputs],['FighterTeamOut','发送客户端脚本信号',inputs],['FighterFlow','监听信号',flowParams],['FighterFlowOut','发送客户端脚本信号',flowParams],['FighterFrames','监听信号',frameParams],['FighterFramesOut','发送客户端脚本信号',frameParams]]){const d=[...defs.values()].find(d=>d.signal===name&&d.kind===kind);assert(d);const portField=kind==='监听信号'?103:102,ps=all(d.data,portField).map(x=>decode(x.v)).filter(x=>params.includes(str(x,1)));assert.deepEqual(ps.map(x=>str(x,1)),params);for(const port of ps)assert.equal(num(msg(port,4),4),str(port,1)==='Payload'?6:3);}
const entries={};let refs=0;
for(const[id,n]of nodes){const base=num(msg(n,2),5),def=defs.get(base);if(def){if(def.kind==='监听信号'){assert(!entries[def.signal]);entries[def.signal]=id;}for(const x of all(n,4)){const a=decode(x.v),customId=num(a,7);if(customId)assert([...all(def.data,100),...all(def.data,101),...all(def.data,102),...all(def.data,103),...all(def.data,106)].some(x=>num(decode(x.v),8)===customId),'Unknown custom port ID');}}
 for(const x of all(n,4)){const a=decode(x.v);if(get(a,2))assert(encode(msg(a,1)).equals(encode(msg(a,2))),'Pin mirrors differ');const link=msg(a,5);if(link.length){refs++;const target=nodes.get(num(link,1));assert(target,'Dangling node reference');if(get(link,3))assert(encode(msg(link,2)).equals(encode(msg(link,3))),'Link mirrors differ');const addr=msg(link,2);if(num(addr,1)===4&&defs.has(num(msg(target,2),5))){const td=defs.get(num(msg(target,2),5));assert(all(td.data,103).map(x=>decode(x.v)).some(p=>num(msg(p,3),1)===4&&num(msg(p,3),2)===num(addr,2)),'Unknown listener output');}}}}
assert.deepEqual(Object.keys(entries).sort(),['FighterHello','FighterTeam','FighterJoin','FighterFrames','FighterFlow'].sort());
// Interpret the actual exported nodes/links, not the compiler's operation list.
function host(){const state={Epoch:1,Stage:1,Round:1,Wins1:0,Wins2:0,P1Revision:-1,P2Revision:-1,P1Ready:0,P2Ready:0};for(const side of[1,2])for(const role of[1,2,3])state['P'+side+'Role'+role]=0;const players=[301,502],sent=[];let event;
 const data=(n,k,i=0)=>{const a=pin(n,k,i);assert(a,'Missing input '+num(n,1)+':'+k+':'+i);const link=msg(a,5);if(link.length)return output(nodes.get(num(link,1)),num(msg(link,2),1),num(msg(link,2),2));const literal=msg(a,3),s=get(literal,105);if(s)return str(decode(s.v),1);assert(!(get(literal,102)&&get(literal,110)),'Invalid direct/generic integer oneof');const int=get(msg(get(literal,110)?msg(msg(literal,110),2):literal,102),1);if(int)return Number(BigInt.asIntN(32,int.v));return 0;};
 function output(n,k,i){const type=num(msg(n,2),5),d=defs.get(type);if(d){assert.equal(d.kind,'监听信号');assert.equal(d.signal,event.signal,'Cross-event input');const port=all(d.data,103).map(x=>decode(x.v)).find(p=>num(msg(p,3),1)===k&&num(msg(p,3),2)===i);assert(port);return event.params[str(port,1)];}
  if(type===73)return 'controller';if(type===248)return players;if(type===142)return data(n,3,0).length;if(type===128)return data(n,3,0)[data(n,3,1)];if(type===50){assert.equal(data(n,3,0),'controller');return state[data(n,3,1)]??0;}if(type===14)return data(n,3,0)===data(n,3,1);if(type===232)return data(n,3,0)>data(n,3,1);if(type===233)return data(n,3,0)>=data(n,3,1);throw Error('Unsupported data node '+type);}
 function next(n,index=0){const a=pin(n,2,index);return a?num(msg(a,5),1):0;}
 const receive=(signal,params={})=>{sent.length=0;event={signal,params};let id=entries[signal],steps=0;while(id){assert(++steps<1000,'Execution cycle');const n=nodes.get(id),type=num(msg(n,2),5),d=defs.get(type);if(d?.kind==='监听信号'){id=next(n);continue;}if(d?.kind==='发送客户端脚本信号'){const values={};for(const port of all(d.data,102).map(x=>decode(x.v)))values[str(port,1)]=data(n,3,num(msg(port,3),2));sent.push({signal:d.signal,target:values['目标玩家'],params:Object.fromEntries(Object.entries(values).filter(([k])=>k!=='目标玩家'))});id=next(n);continue;}if(type===22){assert.equal(data(n,3,0),'controller');state[data(n,3,1)]=data(n,3,2);id=next(n);continue;}if(type===2){const result=data(n,3,0);if(event.signal==="FighterTeam"&&!result)console.log("STOP BRANCH",num(n,1),JSON.stringify(state));id=next(n,result?0:1);continue;}throw Error('Unsupported exec node '+type);}return structuredClone(sent);};return{receive,state,players};}
const h=host(),checks=[];const passed=name=>checks.push(name);let s=h.receive('FighterHello');assert.deepEqual(s.map(x=>[x.target,x.params.Slot]),[[301,1],[502,2]]);passed('Hello: list0/1 to Slot1/2');
const team=(Slot,Revision,Ready,extra={})=>({Slot,Role1:Slot===1?14:18,Role2:Slot===1?19:11,Role3:Slot===1?8:13,Ready,Stage:120,Epoch:1,Revision,Round:1,Wins1:0,Wins2:0,...extra});
assert.equal(h.receive('FighterTeam',team(1,0,0)).length,2);assert.equal(h.state.P1Revision,0);passed('Initial Revision0 accepted against -1');
assert.equal(h.receive('FighterJoin',{Epoch:1}).length,0);h.receive('FighterTeam',team(1,1,2));assert.equal(h.receive('FighterJoin',{Epoch:1}).length,0);passed('One ready does not start');
h.receive('FighterTeam',team(2,0,2));assert.equal(h.receive('FighterJoin',{Epoch:1}).length,2);assert.equal(h.receive('FighterJoin',{Epoch:1}).length,2);passed('Both ready starts; repeated Join may retransmit');
const frame={Slot:1,FirstFrame:0,AckFrame:0,Payload:'raw-payload',Epoch:1};s=h.receive('FighterFrames',frame);assert.equal(s.length,1);assert.equal(s[0].target,502);assert.deepEqual(s[0].params,frame);assert.equal(h.receive('FighterFrames',{...frame,Slot:2})[0].target,301);passed('Frame cross-routing; five parameters including raw string');
assert.equal(h.receive('FighterFrames',{...frame,Slot:3}).length,0);assert.equal(h.receive('FighterFrames',{...frame,Epoch:0}).length,0);passed('Invalid Slot and stale frame Epoch dropped');
assert.equal(h.receive('FighterTeam',team(1,0,2)).length,0);assert.equal(h.receive('FighterTeam',team(1,1,2)).length,2);passed('Old revision dropped; equal revision rebroadcast');
for(const invalid of[{Stage:0},{Stage:211},{Role1:20},{Role1:0},{Role2:14},{Ready:4},{Round:0},{Wins1:3}])assert.equal(h.receive('FighterTeam',team(1,2,2,invalid)).length,0);passed('Parameter ranges and locked team completeness/distinctness');
h.receive('FighterTeam',team(1,0,1,{Epoch:2,Round:2,Wins1:1}));assert.equal(h.state.Epoch,2);assert.equal(h.state.P2Ready,0);assert.equal(h.state.P2Revision,-1);assert.equal(h.receive('FighterJoin',{Epoch:2}).length,0);assert.equal(h.receive('FighterFrames',frame).length,0);passed('New Epoch clears both preparation/revision and old inputs');
assert.equal(h.receive('FighterTeam',team(2,5,2)).length,0);passed('Old Team Epoch cannot restore old ready');
h.receive('FighterTeam',team(1,1,2,{Epoch:2,Round:2,Wins1:1}));s=h.receive('FighterTeam',team(2,0,2,{Epoch:2,Stage:30,Round:3,Wins1:0,Wins2:2}));assert.equal(h.state.Stage,120);assert.equal(h.state.Round,2);assert.equal(h.state.Wins1,1);assert.equal(h.state.Wins2,0);assert(s.every(x=>x.params.Stage===120&&x.params.Round===2));passed('P2 mirrors cannot overwrite P1 scene/round/scores');
assert.equal(h.receive('FighterJoin',{Epoch:1}).length,0);assert.equal(h.receive('FighterJoin',{Epoch:2}).length,2);passed('Next round requires current Epoch and both loaded');
for(const Action of[2,3]){const params={Slot:2,Action,Epoch:1,Revision:3};s=h.receive('FighterFlow',params);assert.equal(s.length,2);assert.deepEqual(s[0].params,params);}passed('Exit/reselect notifications preserve old Epoch for client reorder checks');
assert.equal(h.receive('FighterFlow',{Slot:1,Action:1,Epoch:1,Revision:0}).length,0);assert.equal(h.receive('FighterFlow',{Slot:1,Action:1,Epoch:2,Revision:0}).length,2);assert.equal(h.receive('FighterFlow',{Slot:3,Action:2,Epoch:2,Revision:0}).length,0);passed('Rematch exact Epoch, valid Flow action/slot');
const fresh=host();fresh.players.splice(1);assert.equal(fresh.receive('FighterHello').length,1);assert.equal(fresh.state.P1,301);passed('One player receives seat1 without reading list1');
const referencedVars=[...new Set([...nodes.values()].filter(n=>[22,50].includes(num(msg(n,2),5))).map(n=>str(msg(msg(pin(n,3,1),3),105),1)))].sort();assert.equal(referencedVars.length,17);assert(!referencedVars.includes('Started'));passed('Exactly17 variables; no permanent Started gate');
writeFileSync(out+'/verification.json',JSON.stringify({file:delivery.filename,losslessWireRoundtrip:true,headerSizesValid:true,allCustomPinsResolve:true,allNodeReferencesResolve:true,definedSignals:10,referencedVariables:referencedVars,nodeCount:nodes.size,referenceCount:refs,tests:checks,executionValidation:'Independent interpreter of exported binary nodes using semantics from official samples',exitEpochFiltering:'Current client performs +/-1 range and Flow revision checks',officialImportVerified:false,deviceVerified:false},null,2));console.log(JSON.stringify({file:delivery.filename,testsPassed:checks.length,nodes:nodes.size,refs,variables:referencedVars.length,officialImportVerified:false}));
