import{readFileSync,writeFileSync}from'node:fs';import assert from'node:assert/strict';
import{createStudio}from'file:///C:/Users/Cheng/Documents/deepseek-harness/default-workspace/miliastra-beyond-simulator/studio/index.js';
import{renderPaintPng}from'file:///C:/Users/Cheng/Documents/deepseek-harness/default-workspace/miliastra-beyond-simulator/studio/host-png.js';
const out='outputs/test-v1',save=JSON.parse(readFileSync(out+'/fighter.save.json'));save.assets.scripts[0].source=save.assets.scripts[0].source.replace('local PIXEL_TEMPLATE_INDEX=1073741845','local PIXEL_TEMPLATE_INDEX=0');
const check=s=>{const r=s.playGet({view:true});assert.equal(r.logs.filter(l=>['error','lua-error'].includes(l.level)||/ERROR|失败/.test(l.text||'')).length,0,JSON.stringify(r.logs.slice(-8)));return r;};
const step=(s,n)=>{for(let i=0;i<n;i++)s.playStep(1/60,{observe:false});return check(s);};
const click=(s,p,name)=>{s.playSetView(p);s.playClick(name,{observe:false});};
const node=(s,name)=>check(s).scene.nodes.find(n=>n.name===name);
const until=(s,name)=>{for(let n=0;n<1800;n++){if(node(s,name))return;s.playStep(1/60,{observe:false});}assert.fail('timeout '+name);};
const s=createStudio(save);s.playStart({playerCount:2});step(s,140);
console.log(check(s).logs.slice(-6));assert.ok(node(s,'StartDuel'),'menu load did not complete');
for(let p=1;p<=2;p++)click(s,p,'StartDuel');step(s,3);
click(s,1,'ReadyConfirm');step(s,5);assert.ok(node(s,'ReadyConfirm'),'one ready cannot start');
click(s,2,'ReadyConfirm');until(s,'Timer');step(s,100);assert.ok(!node(s,'Light'),'PC touch buttons visible');
click(s,1,'CommandToggle');step(s,1);assert.ok(node(s,'CommandBody'));click(s,1,'CommandClose');step(s,1);
let r=s.playGet({view:true,paint:true});writeFileSync(out+'/battle.png',renderPaintPng(r.paint,r.canvasWidth,r.canvasHeight).data);
click(s,1,'ExitMatch');until(s,'StartDuel');s.playSetView(2);until(s,'StartDuel');
for(let p=1;p<=2;p++){click(s,p,'StartDuel');click(s,p,'ReadyConfirm');}until(s,'Timer');
writeFileSync(out+'/verification.json',JSON.stringify({simulatorOnly:true,menuLoaded:true,singleReadyDoesNotStart:true,battleLoaded:true,pcTouchHidden:true,commandTable:true,exitAndUnload:true,peerExit:true,reload:true},null,2));console.log('TEST_V1_FLOW_PASS');
