import fs from 'node:fs';import assert from 'node:assert/strict';import {Worker} from 'node:worker_threads';import {createRequire} from 'node:module';import {renderScenePng} from '../vendor/simulator/studio/host-png.js';
const require=createRequire(import.meta.url),canvas=require.resolve('@napi-rs/canvas');
const project=JSON.parse(fs.readFileSync('dist/projects/raiden-nahida.json'));
project.assets.scripts[0].source=project.assets.scripts[0].source.replace("GF_FIRST_SCENE='intro'","GF_FIRST_SCENE='fight'");
project.assets.scripts[0].source=project.assets.scripts[0].source.replace('cpu={2,2}','cpu={false,false}');
project.assets.scripts[0].source+=`\nlocal originalUpdate=OnUpdate\nlocal checked=false\nfunction OnUpdate(dt)\n originalUpdate(dt)\n if not checked and app and app.scene and app.scene.state=='run' and app.scene.sim then\n checked=true\n local S=require('gf_sim');local AI=require('gf_ai');local R=require('gf_roster');local by={} for _,v in ipairs(R) do by[v.key]=v end\n local function duel(seed)\n local s=S.new({chars={by.raidenshogun,by.nahida},rounds=2,time=99,seed=seed});local a,b=AI.new(s,1,3,seed+1),AI.new(s,2,3,seed+2);local n,hits,blocks,rounds=0,0,0,0;local throws={0,0}\n while s.phase~='over' and n<24000 do s:step(a:tick(),b:tick());n=n+1;for _,e in ipairs(s.events) do if e.type=='hit' then hits=hits+1;if e.kind=='throw' then throws[e.by]=throws[e.by]+1 end elseif e.type=='block' then blocks=blocks+1 elseif e.type=='roundEnd' then rounds=rounds+1 end end end\n print('AI THROWS seed='..seed..' count='..throws[1]..'/'..throws[2]);assert(throws[1]+throws[2]>0,'AI never used throw');assert(s.phase=='over','match did not finish');assert(hits>10,'not enough real hits');assert(rounds>=2,'missing rounds');return s:hash(),n,hits,blocks,rounds\n end\n local hash,n,hits,blocks,rounds=duel(21);local hash2,n2=duel(21);assert(hash==hash2 and n==n2,'nondeterminism')\n for _,seed in ipairs({3,11,37}) do duel(seed) end\n local function burstTest(block,invul)\n local s=S.new({chars={by.raidenshogun,by.nahida},time=99});s.phase='fight';s.phaseT=0\n for _,p in ipairs(s.f) do s:setState(p,'idle') end\n local p,d=s.f[1],s.f[2];p.x,d.x=0,14000;p.energy=100;d.invul=invul or 0;s:startBurst(p);local count,first,last=0,nil,nil\n for i=1,400 do s:step(0,block and S.B.R or 0);for _,e in ipairs(s.events) do if (e.type=='hit' or e.type=='block') and e.by==1 then count=count+1;first=first or p.t;last=p.t end end end\n assert(count==(invul==21 and 0 or block and 1 or 3),'Raiden cinematic hit count');if first then assert(first==2,'first hit confirmation') end;if not block and invul==0 then assert(last==70,'cinematic final hit') end;return first,last\n end\n burstTest(false,0);burstTest(true,0);burstTest(false,21)
 local function fresh()
  local s=S.new({chars={by.raidenshogun,by.nahida},time=99});s.phase='fight';s.phaseT=0;for _,p in ipairs(s.f) do s:setState(p,'idle');p.invul=0 end;return s
 end
 for id=1,2 do
  local s=fresh();local p,d=s.f[id],s.f[3-id];p.x=0;d.x=p.face*14000
  s:tryThrow(p);assert(p.state=='throw' and d.state=='thrown','throw should start');for i=1,180 do s:step(0,0) end
  assert(d.hp<d.maxhp and not d.ko and d.state=='idle','throw receiving and getup failed')
 end
 local s=fresh();s.f[1].x=0;s.f[2].x=10000;s:startMove(s.f[1],'light1');local blocks=0
 for i=1,35 do s:step(0,S.B.R);for _,e in ipairs(s.events) do if e.type=='block' then blocks=blocks+1 end end end
 assert(blocks>=1 and s.f[2].hp==s.f[2].maxhp,'normal guard failed')
 for id=1,2 do
  local s=fresh();local p,d=s.f[id],s.f[3-id];p.x=0;d.x=p.face*10000;assert(s:startSkill(p),'E start');assert(not s:startSkill(p),'E cooldown')
  for i=1,100 do s:step(0,0) end;assert(d.hp<d.maxhp,'E damage')
 end\n local s=S.new({chars={by.raidenshogun,by.nahida},time=99});for _,p in ipairs(s.f) do p.ko=true;p.hp=0 end;s:startRound(false);for _,p in ipairs(s.f) do assert(not p.ko and p.hp==p.maxhp,'reset') end\n app.scene.sim.f[1].energy=100;app.scene.sim.f[2].energy=100;app.scene.sim.phase='fight';app.scene.sim.f[1].x=-14000;app.scene.sim.f[2].x=14000;for _,p in ipairs(app.scene.sim.f) do app.scene.sim:setState(p,'idle') end\n print('GFTEST PASS duel='..n..' hits='..hits..' blocks='..blocks..' rounds='..rounds..' deterministic=1 QthreeHits=1 Qblock=1 QinvulMiss=1 reset=1 throwBoth=1 getupBoth=1 guard=1 skillBoth=1')\n end\nend\n`;
const worker=new Worker(`const {parentPort}=require('node:worker_threads');globalThis.OffscreenCanvas=function(w,h){return require(${JSON.stringify(canvas)}).createCanvas(w,h)};globalThis.postMessage=v=>parentPort.postMessage(v);let q=[];parentPort.on('message',data=>globalThis.onmessage?globalThis.onmessage({data}):q.push(data));import(${JSON.stringify('file://'+process.cwd()+'/dist/editor/simulator-worker.js')}).then(()=>{for(const data of q)globalThis.onmessage({data})});`,{eval:true});
let seq=0;const pending=new Map();worker.on('message',r=>{const p=pending.get(r.id);if(!p)return;pending.delete(r.id);r.ok?p.resolve(r.value):p.reject(Error(r.error));});worker.on('error',e=>{for(const p of pending.values())p.reject(e);});
const call=(action,body={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});worker.postMessage({id,action,body});});
let logs=[];async function observe(){const s=await call('play',{action:'get',args:{view:true,compact:true}});assert.equal(s.mountError,null);const errors=s.logs.filter(l=>(l.level==='error'||l.level==='lua-error'));assert.equal(errors.length,0,JSON.stringify(errors));logs=s.logs;return s;}
async function step(n){for(let i=0;i<n;i++)await call('play',{action:'step',args:{dt:1/60,light:true}});}
async function capture(name){const s=await observe();const im=renderScenePng(s.scene,s.canvasWidth,s.canvasHeight);fs.mkdirSync('verification/dual-character',{recursive:true});fs.writeFileSync('verification/dual-character/'+name+'.png',im.data);return s;}
try{await call('import',{format:'json',filename:'raiden-nahida.json',data:Buffer.from(JSON.stringify(project)).toString('base64')});await call('play',{action:'start'});await call('play',{action:'pause'});await step(600);let s=await capture('match-start');assert(logs.some(l=>l.text.includes('GFTEST PASS')),JSON.stringify(logs.slice(-5)));console.log(logs.filter(l=>l.text.includes('GFTEST PASS')||l.text.startsWith('AI THROWS')).map(l=>l.text).join('\n'));
await step(10);await call('play',{action:'key',args:{key:'KeyboardCharacterSkill2KeyDown'}});await step(21);await capture('raiden-q');await call('play',{action:'key',args:{key:'KeyboardCharacterSkill2KeyUp'}});await step(90);await call('play',{action:'key',args:{key:'KeyboardCharacterSkill1KeyDown'}});await step(17);await capture('raiden-e');await call('play',{action:'key',args:{key:'KeyboardCharacterSkill1KeyUp'}});await step(180);await call('play',{action:'key',args:{key:'KeyboardCraftspersonKey41Down'}});await step(78);await capture('nahida-q');await call('play',{action:'key',args:{key:'KeyboardCraftspersonKey41Up'}});await step(90);await capture('battle');await call('play',{action:'device',args:{canvasId:'mobile-16-9'}});await step(650);const mobile=await capture('mobile');assert(mobile.scene,'mobile scene missing');
fs.writeFileSync('verification/dual-character/report.json',JSON.stringify({method:'Actual bundled Lua runtime and Worker RPC, CPU raster; no browser or official client QA',checks:logs.filter(l=>l.text.includes('GFTEST')).map(l=>l.text),screenshots:['match-start','raiden-q','raiden-e','nahida-q','battle','mobile']},null,2));console.log('PASS engine mount, actual Lua battles, deterministic replay and screenshots');}finally{await worker.terminate();}
