(()=>{'use strict';const $=id=>document.getElementById(id),D=window.PROBE_DATA,M=window.ProbeModel,c=$('stage'),ctx=c.getContext('2d');
let preview='attack';const stateNames={attack:'招式演示',idle:'待机',walk:'走路',crouch:'蹲下',guard:'站立防御',crouchGuard:'蹲伏防御',hurt:'受击',airHurt:'浮空',down:'倒地',getup:'起身',jump:'跳跃'};
let selected=D.roles[0],action='A',frame=0,playing=true,previous=0,acc=0,edited={},images=new Map(),move=null,uploadUrl=null;const numeric=['startup','active','recovery','reach','damage','blockstun','hitstun','effectExtent'];const names={startup:'起手帧',active:'有效帧',recovery:'收招帧',reach:'最远距离',damage:'总伤害',blockstun:'防御硬直',hitstun:'受击硬直',effectExtent:'特效外缘'};
const image=url=>{if(!images.has(url)){const im=new Image();im.src=url;images.set(url,im);}return images.get(url);};
function fallback(){return{name:'现有姿势查看',startup:12,active:4,recovery:20,reach:130,damage:0,blockstun:0,hitstun:0,effectExtent:130,fx:'none',notes:'此角色未完成本轮动作研究；这里仅查看现有姿势。参数是探针查看默认值，不作为该角色设计。',support:true};}
function candidate(){const m=structuredClone(selected.design?.moves[action]||fallback());if(selected.key==='diluc'&&action==='E'){const n=Number($('chain').value);Object.assign(m,n===2?{startup:17,active:4,recovery:25,reach:170,damage:14,effectExtent:195}:n===3?{startup:22,active:5,recovery:32,reach:180,damage:18,effectExtent:205}:{});}return m;}
function updateMove(){const key=selected.key+':'+action+':'+$('chain').value;move=edited[key]||(edited[key]=candidate());$('chainLabel').hidden=!(selected.key==='diluc'&&action==='E');if(selected.key==='diluc'&&action==='E'){const stage=Number($('chain').value);move.stage=stage;move.name=['逆焰之刃 · 前斜劈','逆焰之刃 · 回扫','逆焰之刃 · 下砸'][stage-1];}frame=0;acc=0;$('scrub').max=M.duration(move);$('notes').textContent=move.notes+'  取消规则：'+(move.cancel||'待研究');$('numbers').replaceChildren();for(const key of numeric){const label=document.createElement('label');label.textContent=names[key];const input=document.createElement('input');input.type='number';input.min=key==='damage'||key.includes('stun')?0:1;input.max=key.includes('stun')||['startup','active','recovery'].includes(key)?600:1000;input.value=move[key]??0;input.oninput=input.onchange=()=>{move[key]=Math.max(key==='damage'||key.includes('stun')?0:1,Math.min(1000,Number(input.value)||0));$('scrub').max=M.duration(move);timeline();};label.append(input);$('numbers').append(label);}timeline();renderMoves();}
function renderRoles(){const query=$('search').value.trim();$('roles').replaceChildren();for(const r of D.roles.filter(r=>(!$('studied').checked||r.design)&&r.name.includes(query))){const b=document.createElement('button');b.className=r===selected?'active':'';if(r.head){const im=document.createElement('img');im.src=r.head;im.alt='';b.append(im);}b.append(document.createTextNode(r.name));b.onclick=()=>choose(r);$('roles').append(b);}}
function choose(r){preview='attack';selected=r;images=new Map();action='A';$('roleTitle').textContent=r.name;$('identity').textContent=r.design?.identity||'现有素材 · 动作研究尚未展开';$('original').textContent=r.originalSkills?'原作名称：特殊技参考 '+r.originalSkills.E+'；必杀参考 '+r.originalSkills.Q:'原作名称见素材记录';$('pose').replaceChildren(new Option('按动作自动切换','auto'),...r.poses.map(p=>new Option(p.name+(p.alias?' · 代用':''),p.name)));reference();renderRoles();renderStates();updateMove();}
function renderStates(){$('states').replaceChildren();for(const[key,name]of Object.entries(stateNames)){const b=document.createElement('button');b.textContent=name;b.className=preview===key?'active':'';b.onclick=()=>{preview=key;frame=0;acc=0;playing=true;$('play').textContent='暂停';$('scrub').max=key==='attack'?M.duration(move):120;renderStates();};$('states').append(b);}}
function renderMoves(){$('moves').replaceChildren();for(const k of['A','E','Q']){const b=document.createElement('button');b.textContent=({A:'普攻',E:'特殊技',Q:'必杀'})[k]+' · '+(selected.design?.moves[k].name||'未研究');b.className=action===k?'active':'';b.onclick=()=>{preview='attack';action=k;renderStates();updateMove();};$('moves').append(b);}}
function timeline(){const total=M.duration(move);$('timeline').replaceChildren();for(const[label,n,color]of[['起手',move.startup,'#a86d50'],['有效',move.active,'#48966f'],['收招',move.recovery,'#665e89'],[move.effectDuration?'领域':'飞行',Math.max(0,total-move.startup-move.active-move.recovery),'#3a84a2']]){if(!n)continue;const el=document.createElement('span');el.className='segment';el.textContent=label;el.style.flex=n;el.style.background=color;$('timeline').append(el);}}
function reference(){$('reference').replaceChildren();if(selected.design?.video){const a=document.createElement('a');a.href=selected.design.video;a.target='_blank';a.rel='noopener';a.textContent='原神官方技能演示';$('reference').append(a);}else{$('reference').textContent='本轮此角色以已有技能资料研究；官方实机截图仍待补齐。';}$('referenceImages').replaceChildren();const r=D.references.find(r=>r.key===selected.key&&r.samples);if(r){for(const s of r.samples){const im=document.createElement('img');im.src='../../'+s.path;im.title=s.seconds+' 秒 · 原作实机抽帧';im.alt=selected.name+' '+s.seconds+'秒';im.onclick=()=>{const a=document.createElement('a');a.href=im.src;a.target='_blank';a.rel='noopener';a.click();};$('referenceImages').append(im);}const link=document.createElement('a');link.href='../../'+r.path;link.textContent='查看本地原作录像';link.target='_blank';$('reference').append(link);}}
function line(x1,y1,x2,y2,color,width=3){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();}
function rig(x,dummy=false){if(!dummy&&preview!=='attack'){basicRig(x);return;}if(!dummy&&window.MotionStudy?.draw({ctx,role:selected,action,move,frame,model:M,x}))return;ctx.save();ctx.scale(1,1.25);drawRig(x,dummy);ctx.restore();}
function drawRig(x,dummy=false){const color=dummy?'#85b9d0':(selected.design?.color||'#c1bfdc'),ph=M.stateAt(move,frame),t=frame-move.startup,u=M.clamp(t/Math.max(1,move.active),0,1);let lean=dummy?0:ph==='起手'?-7:ph==='有效'?12:4;let lift=0;if(!dummy&&move.fx==='plunge'&&frame>10&&frame<move.startup)lift=Math.sin(frame/move.startup*Math.PI)*130;
 const Y=v=>-v-lift;ellipse(x,0,35,7,'#070d1688');line(x-9,Y(76),x-22,Y(8),color,13);line(x+8,Y(76),x+23,Y(8),color,13);poly([[x-20,Y(78)],[x+21,Y(78)],[x+15+lean,Y(139)],[x-14+lean,Y(139)]],color);poly([[x-20,Y(77)],[x+23,Y(77)],[x+32,Y(49)],[x-31,Y(49)]],dummy?'#304960':'#34465c');ellipse(x+lean,Y(164),18,22,color);line(x+lean-9,Y(148),x+lean+8,Y(148),'#efe4d1',3);
 const shoulder=[x+lean+12,Y(128)],back=[x+lean-12,Y(128)];let hand=[x+40,Y(110)];if(!dummy){if(action==='A'||selected.design?.weapon==='claymore'){const angle=(ph==='起手'?-1.9:ph==='有效'?-.9+u*1.9:.55);hand=[x+lean+27+Math.cos(angle)*25,Y(115)-Math.sin(angle)*24];}else if(move.fx==='beam'){hand=[x+43,Y(130)];}else if(['shrine','mark','totem'].includes(move.fx)){hand=[x+50,Y(145)];}else{hand=[x+40,Y(125)];}}else if($('dummy').value==='guard'||$('dummy').value==='ai'&&frame>=18)hand=[x-30,Y(142)];
 line(...shoulder,...hand,color,9);line(...back,x-35,Y(108),color,8);
 if(dummy)return;
 const w=selected.design?.weapon;if(['sword','claymore','polearm','dual'].includes(w)){const size=w==='polearm'?145:w==='claymore'?110:w==='dual'?55:85;let a=ph==='起手'?-2.2:ph==='有效'?-1.2+u*1.7:.25;if(move.stage===2)a=ph==='有效'?.6-u*1.8:-.9;if(move.stage===3)a=ph==='有效'?-1.8+u*2.6:-1.8;const tip=[hand[0]+Math.cos(a)*size,hand[1]+Math.sin(a)*size];line(hand[0]-Math.cos(a)*14,hand[1]-Math.sin(a)*14,...tip,w==='claymore'?'#d3d4e1':'#e5ebf5',w==='claymore'?12:4);line(hand[0]-9,hand[1]+7,hand[0]+9,hand[1]-7,'#d0b682',5);if(w==='dual')line(x-32,Y(111),x-5,Y(163),'#83d9ef',4);
 }else if(w==='bow'){ctx.strokeStyle='#c7b58a';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x+42,Y(121),40,-1.25,1.25);ctx.stroke();line(x+55,Y(161),x+55,Y(82),'#dce7ed',1);}
}
function statePose(){if(preview==='idle')return 'idle';if(preview==='walk')return Math.floor(frame/10)%2?'walk2':'walk1';if(preview==='down')return frame<10?'hurt':frame<22?'airHurt':'down';if(preview==='getup')return frame<16?'down':frame<40?'getup':'idle';return preview;}
function basicRig(x){const mode=statePose(),col=selected.design?.color||'#b6cce1',phase=frame*.12,bob=mode==='idle'?Math.sin(phase)*2:0;if(mode==='down'){ellipse(x+45,-15,76,16,col);line(x-20,-14,x+98,-15,col,12);ellipse(x-30,-24,18,22,col);return;}const crouch=mode==='crouch'||mode==='crouchGuard',rise=mode==='getup'?Math.min(1,(frame-16)/24):1,lift=mode==='jump'?Math.sin(Math.min(1,frame/60)*Math.PI)*120:mode==='airHurt'?Math.max(0,100-Math.abs(frame-16)*4):0,hip=crouch?-58:mode==='getup'?-58-47*rise:-105,head=crouch?-127:mode==='getup'?-127-77*rise:-204,lean=mode==='hurt'?-18:mode==='walk'?7:0;ctx.save();ctx.translate(x,-lift+bob);if(mode==='airHurt')ctx.rotate(-.45);ellipse(lean,head,18,23,col);line(lean,head+24,0,hip,col,27);const swing=mode==='walk'?Math.sin(phase)*19:0;line(-10,hip,-24+swing,-48,col,12);line(-24+swing,-48,-30+swing,0,col,11);line(10,hip,27-swing,-48,col,12);line(27-swing,-48,35-swing,0,col,11);line(lean-12,head+42,-30,hip+5,col,9);line(lean+12,head+42,['guard','crouchGuard'].includes(mode)?42:35,['guard','crouchGuard'].includes(mode)?head+22:hip+10,col,9);ctx.restore();}
function pixel(x){let pose=$('pose').value;if(preview!=='attack')pose=statePose();if(pose==='auto'){const phase=M.stateAt(move,frame);pose=phase==='起手'?(action==='Q'?'qCharge':'windup'):phase==='有效'?(action==='A'?'slash':action==='Q'?'qRelease':'special'):'idle';if(selected.key==='keqing'&&action==='E'&&phase==='有效')pose='teleport';if(selected.key==='diluc'&&action==='E'&&phase==='有效')pose='e'+(move.stage||1);}
 const exact=selected.poses.find(p=>p.name===pose);if(preview!=='attack'&&(!exact||exact.alias)){basicRig(x);return {name:pose+' · 结构代用',rectangles:0,alias:true};}const f=exact||selected.poses.find(p=>p.name==='idle')||selected.poses[0],im=image(f.url);ctx.imageSmoothingEnabled=false;if(im.complete&&im.naturalWidth){const bob=preview==='idle'?Math.sin(frame*.09)*1.6:0;ctx.drawImage(im,x-f.anchor[0]*f.scale,-f.anchor[1]*f.scale+bob,f.w*f.scale,f.h*f.scale);}return f;}
function effects(){if(preview!=='attack')return;if($('fxVersion').value==='v2'&&window.ProbeFX?.draw({ctx,move,frame,role:selected,model:M,low:$('quality').value==='low',action,contact:M.sample(move,Math.floor(frame),Number($('distance').value),$('dummy').value),distance:Number($('distance').value),motion:window.MotionStudy}))return;const t=frame-move.startup;if(frame===0||t>Math.max(move.active,move.flight||0,move.effectDuration||0))return;const col=selected.design?.color||'#aad4ee',low=$('quality').value==='low';ctx.save();ctx.beginPath();ctx.rect(-move.effectExtent,-330,move.effectExtent*2,350);ctx.clip();ctx.globalAlpha=t<=0?.25:1;ctx.shadowColor=col;ctx.shadowBlur=low?0:10;
 const x=M.actorOffset(move,frame),fx=move.fx,reach=move.reach;
 if(t<=0){ellipse(x+24,-100,10+frame%12,10+frame%12,col+'66');ctx.restore();return;}
 if(['slash','fireblade','dual','thrust','lightning','dash','afterimage','butterfly'].includes(fx)){if(fx==='thrust'||fx==='dash')line(x+30,-95,reach,-95,col,fx==='dash'?12:5);else{const n=fx==='afterimage'?6:fx==='dual'?2:1;for(let i=0;i<n;i++){const dy=fx==='afterimage'?i*17-40:i*20;ctx.strokeStyle=fx==='fireblade'?'#ffaf51':col;ctx.lineWidth=low?4:7;ctx.beginPath();ctx.ellipse(x+(reach-x)*.5,-100+dy,(reach-x)*.48,45,i*.28,-1.7,1.3);ctx.stroke();}}if(fx==='afterimage'&&!low)for(let i=0;i<3;i++){ctx.globalAlpha=.16;ctx.translate(-24,0);rig(x);}if(fx==='butterfly'){ctx.globalAlpha=.5;for(let i=0;i<7;i++)ellipse(x-i*17,-65+Math.sin(i)*18,6,3,col);}}
 else if(fx==='phoenix'){const b=M.hitboxes(move,frame)[0];if(b){const bx=b.x+25;poly([[bx-50,-90],[bx-8,-132],[bx+23,-115],[bx+55,-100],[bx+20,-88],[bx-5,-68]],'#ffcb66');poly([[bx-16,-112],[bx-83,-175],[bx-35,-140],[bx+10,-104]],'#ff893f');poly([[bx-15,-99],[bx-84,-34],[bx-30,-74],[bx+8,-107]],'#ff9e47');for(let i=0;i<(low?3:7);i++)line(bx-40-i*13,-95+Math.sin(i)*20,bx-80-i*15,-92+Math.sin(i)*35,'#e9683b',5);}}
 else if(fx==='beam'){const g=ctx.createLinearGradient(x+25,0,reach,0);g.addColorStop(0,'#b9f6ff');g.addColorStop(1,'#55bcff88');ctx.fillStyle=g;ctx.fillRect(x+25,-148,Math.max(0,reach-x-25),74);for(let i=0;i<(low?2:6);i++)line(x+30,-130+i*9+Math.sin(frame*.3+i)*5,reach,-130+i*9,col,2);ellipse(x+35,-112,22,50,'#cff8ff88');}
 else if(fx==='shrine'){ctx.globalAlpha=.28;ctx.strokeStyle=col;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,-8,reach,reach*.85,0,Math.PI,0);ctx.stroke();ctx.beginPath();ctx.ellipse(0,-8,reach,18,0,0,Math.PI*2);ctx.stroke();for(let i=0;i<(low?4:10);i++){const a=i*Math.PI/(low?4:10),px=Math.cos(a)*reach;line(px,-Math.sin(a)*reach*.85,px*.65,-55,col,2);}ctx.globalAlpha=.7;ellipse(0,-10,10,4,col);}
 else if(fx==='stiletto'){const bx=t<4?Math.min(reach,t*65):reach;poly([[bx-10,-105],[bx+15,-100],[bx-10,-95],[bx-3,-100]],col);line(20,-100,bx,-100,col+'88',2);if(t>=2)line(x+10,-155,x+85,-55,col,5);}
 else if(['arrow','bomb','bounce'].includes(fx)){const b=M.hitboxes(move,frame)[0];if(b){const bx=b.x+b.w/2,by=-b.y-b.h/2;if(fx==='arrow')line(bx-24,by,bx+20,by,col,4);else{ellipse(bx,by,fx==='bounce'?23:12,fx==='bounce'?23:12,'#ffbc72');line(bx+5,by-8,bx+10,by-20,'#f3ece2',3);}}}
 else if(fx==='eye'){line(25,-105,reach,-105,col,6);ctx.strokeStyle=col;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(30,-220,40,12,0,0,Math.PI*2);ctx.stroke();ellipse(30,-220,8,8,col);}
 else if(fx==='mark'){ctx.strokeStyle=col;ctx.lineWidth=3;ctx.strokeRect(40,-160,reach-40,110);for(let i=0;i<4;i++)ellipse(60+i*50,-130+(i%2)*35,7,12,col+'88');}
 else if(['meteor','cannon','thunder','waterpillar','icepillar','windpillar','pillar'].includes(fx)){const at=Math.min(reach,160);if(fx==='meteor'){const fall=180*Math.min(1,t/move.active);poly([[at-55,-180+fall],[at-25,-240+fall],[at+55,-210+fall],[at+70,-165+fall]],'#e6bb65');}else for(let i=0;i<(fx==='cannon'?3:1);i++){const dx=at+i*45;line(dx,-240,dx,0,col,fx==='thunder'?9:22);ellipse(dx,-5,25,7,col+'88');}}
 else if(['vortex','blizzard'].includes(fx)){const b=move.projectile?M.hitboxes(move,frame)[0]:null,at=b?b.x+25:move.reach-50;for(let i=0;i<(low?3:7);i++){ctx.strokeStyle=col+(i%2?'88':'dd');ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(at,-100,45-i*3,65+i*3,frame*.06+i*.4,0,Math.PI*2);ctx.stroke();}}
 else if(fx==='totem'){const at=160;poly([[at-18,0],[at-12,-95],[at,-115],[at+14,-95],[at+20,0]],col+'88');ellipse(at,-78,24,7,col);}
 else if(fx==='shotgun'){poly([[25,-113],[reach,-175],[reach,-45]],col+'55');for(let i=0;i<(low?3:9);i++)line(28,-110,reach,-170+i*15,col,2);}
 else if(fx==='ghost'){ellipse(125,-105,54,35,'#ffdbbeaa');ellipse(141,-107,4,6,'#665f7b');ellipse(156,-107,4,6,'#665f7b');}
 else if(fx==='plunge'){line(40,-230,40,-4,col,12);ellipse(40,-8,reach,13,col+'88');}
 else if(fx==='sparks'){for(let i=0;i<3;i++)line(40+i*40,-230,140+i*45,-60,col,5);}
 else if(['water','leaf','fox','wave'].includes(fx)){for(let i=0;i<(low?3:7);i++)ellipse(35+i*reach/8,-95+Math.sin(i+frame*.2)*18,12,fx==='leaf'?7:15,col+'aa');}
 ctx.restore();}
function portraitCutin(){if(preview!=='attack'||action!=='Q'||!selected.portrait||!$('cutin').checked)return;const life=Math.min(24,move.startup),u=frame/life;if(u>=1)return;const alpha=Math.min(1,frame/3,(life-frame)/6),im=image(selected.portrait),color=selected.design?.color||'#b8cce8';ctx.save();ctx.globalAlpha=Math.max(0,alpha);ctx.beginPath();ctx.moveTo(545,68);ctx.lineTo(1100,68);ctx.lineTo(1100,418);ctx.lineTo(465,418);ctx.closePath();ctx.clip();const g=ctx.createLinearGradient(480,0,1100,0);g.addColorStop(0,'#0d1323ee');g.addColorStop(1,color+'77');ctx.fillStyle=g;ctx.fillRect(460,68,640,350);if(im.complete&&im.naturalWidth){ctx.imageSmoothingEnabled=true;ctx.drawImage(im,420+25*(1-u),70,740,370);}line(545,69,1100,69,color,3);ctx.fillStyle='#08121bd0';ctx.fillRect(620,345,480,73);ctx.fillStyle='#fff';ctx.font='22px Microsoft YaHei';ctx.fillText(selected.name+' · '+move.name,645,374);ctx.font='12px Microsoft YaHei';ctx.fillText('半屏立绘实验 · 场上施法姿势独立 · 状态型配套待定',645,399);ctx.restore();}
function draw(){if(!move)return;const distance=Number($('distance').value),dummy=$('dummy').value,res=preview==='attack'?M.sample(move,Math.floor(frame),distance,dummy):{phase:stateNames[preview],box:[],hurt:{x:distance-22,y:0,w:44,h:232},result:'基础姿态演示'},fdir=Number($('direction').value),total=preview==='attack'?M.duration(move):120;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#101a29';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#1c2939';ctx.fillRect(0,408,c.width,112);for(let x=0;x<1100;x+=80)line(x,408,x+15,520,'#2c4050',1);line(0,410,1100,410,'#677b89',2);ctx.save();ctx.translate(fdir===1?170:930,410);ctx.scale(fdir*.9,.9);ctx.save();ctx.translate(distance,dummy==='jump'?-225:0);ctx.scale(-1,1);rig(0,true);ctx.restore();const ax=preview==='attack'?M.actorOffset(move,frame):preview==='walk'?Math.sin(frame*.035)*30:0;let pixelFrame=null;if($('view').value==='pixel')pixelFrame=pixel(ax);else rig(ax);effects();
 if($('boxes').checked){ctx.strokeStyle='#63bbf0';ctx.lineWidth=2;ctx.strokeRect(res.hurt.x,-res.hurt.y-res.hurt.h,res.hurt.w,res.hurt.h);ctx.strokeRect(ax-20,-232,40,232);ctx.fillStyle='#f2697933';ctx.strokeStyle='#f26979';for(const b of res.box){ctx.fillRect(b.x,-b.y-b.h,b.w,b.h);ctx.strokeRect(b.x,-b.y-b.h,b.w,b.h);}ctx.setLineDash([5,5]);line(move.effectExtent,-270,move.effectExtent,0,'#c5a870',1);ctx.setLineDash([]);line(0,15,distance,15,'#aec0ce',1);for(let p=0;p<=660;p+=100)line(p,10,p,20,'#aec0ce',1);}
 ctx.restore();portraitCutin();ctx.font='16px Microsoft YaHei';ctx.fillStyle='#d9e5ef';ctx.fillText(selected.name+' · '+(preview==='attack'?move.name:stateNames[preview]),22,32);ctx.font='13px Microsoft YaHei';ctx.fillStyle='#9dafc0';ctx.fillText('第 '+Math.min(total,Math.floor(frame))+' / '+total+' 帧 · '+res.phase+' · '+res.result,22,57);ctx.fillText('结构示意 / 现有姿势对照 · 不是新完成的像素动画',22,490);
 $('scrub').value=Math.floor(frame);$('phase').textContent=Math.min(total,Math.floor(frame))+' 帧 · '+res.phase;$('distanceValue').value=distance;const trace=preview==='attack'?M.trace(move,Math.min(frame,total),distance,dummy):{events:[],damage:0};$('result').textContent=res.result+' · 本次接触 '+trace.events.length+' 次 / 伤害示意 '+trace.damage.toFixed(1)+' · 对手中心距离 '+distance+' · '+(move.support?'无直接伤害':('总伤害候选 '+move.damage+' / '+(move.hitCount||1)+' 次命中'));const adv=move.blockstun-(move.active-1+move.recovery);$('metrics').textContent='到最远判定 '+move.reach+'；特效外缘 '+move.effectExtent+'；演员前移 '+(move.dash||0)+(move.support?'；布置技能无直接命中硬直':'；首有效帧防御优势示意 '+(adv>=0?'+':'')+adv+'（多段/投射物须按实际接触时刻重算）')+(pixelFrame?'；当前姿势 '+pixelFrame.name+'，图片矩形 '+pixelFrame.rectangles+(pixelFrame.alias?'，代用':''):'');$('aiState').textContent=dummy==='ai'?(frame<18?'观察延迟中，尚未反应':'已观察公开起手，选择防守；无输入读取'):'启用“AI 防守设计示意”可观察反应窗口';
}
function raf(now){const dt=Math.min(.1,(now-previous)/1000||0);previous=now;if(playing&&move){acc+=dt*60*Number($('speed').value);if(acc>=1){frame+=Math.floor(acc);acc%=1;if(frame>(preview==='attack'?M.duration(move)+35:120)){frame=0;}}}draw();requestAnimationFrame(raf);}
$('zoom').onclick=()=>{const large=c.closest('.stage').classList.toggle('expanded');$('zoom').textContent=large?'收起舞台':'放大舞台';};$('search').oninput=renderRoles;$('studied').onchange=renderRoles;$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'暂停':'播放';};$('step').onclick=()=>{playing=false;$('play').textContent='播放';frame=Math.min(preview==='attack'?M.duration(move):120,Math.floor(frame)+1);};$('restart').onclick=()=>{frame=0;acc=0;};$('scrub').oninput=e=>{playing=false;$('play').textContent='播放';frame=Number(e.target.value);};$('chain').onchange=updateMove;$('reset').onclick=()=>{delete edited[selected.key+':'+action+':'+$('chain').value];updateMove();};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').onclick=()=>{const json=JSON.stringify({version:D.version,role:selected.key,action,design:move,reference:selected.design?.video,productionCombatChanged:false},null,2);$('exportPreview').hidden=false;$('exportPreview').open=true;$('exportText').value=json;download(new Blob([json],{type:'application/json'}),'action-design-'+selected.key+'-'+action+'.json');};$('screenshot').onclick=()=>c.toBlob(b=>download(b,'action-probe-'+selected.key+'-'+action+'-'+Math.floor(frame)+'.png'));$('upload').onchange=e=>{const f=e.target.files[0];if(f){if(uploadUrl)URL.revokeObjectURL(uploadUrl);uploadUrl=URL.createObjectURL(f);$('userReference').src=uploadUrl;$('userReference').hidden=false;}};
window.actionProbe={select:key=>choose(D.roles.find(r=>r.key===key)),setAction:k=>{action=k;updateMove();},setFrame:n=>{playing=false;frame=n;draw();},getState:()=>({role:selected.key,action,frame,move:structuredClone(move)}),render:draw};choose(selected);requestAnimationFrame(raf);
})();
